[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build]
  publish = "public"
  command = "npm --version && node --version && npm install && npm list --depth=0 && mkdir -p public/img && cp -r source/img/* public/img/ && hexo clean && hexo generate"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false