[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build]
  publish = "public"
  command = "git submodule update --init --recursive && hexo clean && hexo generate"

[build.environment]
  NODE_VERSION = "16"

# 添加以下特定设置帮助Netlify处理子模块
[build.processing]
  skip_processing = false