[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[build]
  publish = "public"
  command = "npm install && npm install hexo-butterfly-extensions hexo-generator-category && hexo clean && hexo generate"

[build.environment]
  NODE_VERSION = "18"
  WALINE_SERVER_URL = "您的Waline服务地址"
  PARTICLES_COLOR = "#42b983"

[build.processing]
  skip_processing = false